export const REQUEST_EVENTS = 'EVENTS/REQUEST_EONET_EVENTS';
export const REQUEST_EVENTS_START = 'EVENTS/REQUEST_EONET_EVENTS_START';
export const REQUEST_EVENTS_FAILURE = 'EVENTS/REQUEST_EONET_EVENTS_FAILURE';
export const REQUEST_EVENTS_SUCCESS = 'EVENTS/REQUEST_EONET_EVENTS_SUCCESS';

export const REQUEST_SOURCES = 'EVENTS/REQUEST_SOURCES';
export const REQUEST_SOURCES_START = 'EVENTS/REQUEST_SOURCES_START';
export const REQUEST_SOURCES_FAILURE = 'EVENTS/REQUEST_SOURCES_FAILURE';
export const REQUEST_SOURCES_SUCCESS = 'EVENTS/REQUEST_SOURCES_SUCCESS';

export const DESELECT_EVENT = 'EVENTS/DESELECT_EVENT';
export const SELECT_EVENT = 'EVENTS/SELECT_EVENT';
export const SHOW_ALL_EVENTS = 'EVENTS/SHOW_ALL_EVENTS';
export const SELECT_CATEGORY = 'EVENTS/SELECT_CATEGORY';
export const ONLY_SHOW_VISIBLE = 'EVENTS/ONLY_SHOW_VISIBLE';
export const TOGGLE_SHOW_ALL = 'EVENTS/TOGGLE_SHOW_ALL';
export const FINISHED_ANIMATING_TO_EVENT = 'EVENTS/FINISHED_ANIMATING_TO_EVENT';

export const ALL_CATEGORY = 'All Event Categories';
