export const REQUEST_EVENTS = 'EVENTS/REQUEST_EVENTS';
export const REQUEST_EVENTS_START = 'EVENTS/REQUEST_EVENTS_START';
export const REQUEST_EVENTS_FAILURE = 'EVENTS/REQUEST_EVENTS_FAILURE';
export const REQUEST_EVENTS_SUCCESS = 'EVENTS/REQUEST_EVENTS_SUCCESS';

export const REQUEST_SOURCES = 'EVENTS/REQUEST_SOURCES';
export const REQUEST_SOURCES_START = 'EVENTS/REQUEST_SOURCES_START';
export const REQUEST_SOURCES_FAILURE = 'EVENTS/REQUEST_SOURCES_FAILURE';
export const REQUEST_SOURCES_SUCCESS = 'EVENTS/REQUEST_SOURCES_SUCCESS';

export const SET_EVENTS_FILTER = 'EVENTS/SET_FILTER';
export const DESELECT_EVENT = 'EVENTS/DESELECT_EVENT';
export const SELECT_EVENT = 'EVENTS/SELECT_EVENT';
export const ADD_CATEGORY = 'EVENTS/ADD_CATEGORY';
export const REMOVE_CATEGORY = 'EVENTS/REMOVE_CATEGORY';
export const FINISHED_ANIMATING_TO_EVENT = 'EVENTS/FINISHED_ANIMATING_TO_EVENT';

export const LIMIT_EVENT_REQUEST_COUNT = 50;
