export default {
  1: ['MODIS_Terra_CorrectedReflectance_TrueColor'],
  2: ['GOES-East_ABI_GeoColor', 'GOES-West_ABI_GeoColor', 'Himawari_AHI_Band3_Red_Visible_1km'],
  3: ['VIIRS_SNPP_CorrectedReflectance_TrueColor'],
  4: ['VIIRS_SNPP_DayNightBand_At_Sensor_Radiance'],
  5: ['IMERG_Precipitation_Rate'],
  6: ['GHRSST_L4_MUR_Sea_Surface_Temperature'],
  7: ['MODIS_Aqua_Land_Surface_Temp_Day', 'MODIS_Aqua_CorrectedReflectance_TrueColor'],
  8: ['AMSRU2_Sea_Ice_Concentration_12km'],
  9: ['AMSRU2_Sea_Ice_Concentration_12km'],
  10: ['VIIRS_SNPP_CorrectedReflectance_TrueColor'],
  11: ['OMI_Nitrogen_Dioxide_Tropo_Column', 'VIIRS_NOAA20_CorrectedReflectance_TrueColor'],
  12: ['AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Night', 'AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Day'],
  13: ['VIIRS_SNPP_AOT_Dark_Target_Land_Ocean', 'VIIRS_SNPP_AOT_Deep_Blue_Best_Estimate', 'VIIRS_SNPP_CorrectedReflectance_TrueColor'],
};
