export const MEASURE_DISTANCE = 'MAP/MEASURE_DISTANCE';
export const MEASURE_AREA = 'MAP/MEASURE_AREA';
export const ADD_DISTANCE_MEASUREMENT = 'MAP/ADD_DISTANCE_MEASUREMENT';
export const ADD_AREA_MEASUREMENT = 'MAP/ADD_AREA_MEASUREMENT';
export const CLEAR_MEASUREMENTS = 'MAP/CLEAR_MEASUREMENTS';
