export const MEASURE_DISTANCE = 'MAP/MEASURE_DISTANCE';
export const MEASURE_AREA = 'MAP/MEASURE_AREA';
export const CHANGE_UNIT_OF_MEASURE = 'MAP/CHANGE_UNIT_OF_MEASURE';
export const CLEAR_MEASUREMENTS = 'MAP/CLEAR_MEASUREMENTS';
