export const CHANGE_TAB = 'CHANGE_ACTIVE_SIDEBAR_TAB';

export const TOGGLE_COLLAPSE = 'TOGGLE_SIDEBAR_COLLAPSE_EXAPND';
export const COLLAPSE_SIDEBAR = 'SIDEBAR_COLLAPSE_NOW';
export const EXPAND_SIDEBAR = 'SIDEBAR_EXPAND_NOW';
