export const TOGGLE_DISTRACTION_FREE_MODE = 'UI/TOGGLE_DISTRACTION_FREE_MODE';
export const TOGGLE_KIOSK_MODE = 'UI/TOGGLE_KIOSK_MODE';
export const SET_ERROR_TILES = 'UI/SET_ERROR_TILES';
export const CLEAR_ERROR_TILES = 'UI/CLEAR_ERROR_TILES';
