#!/bin/bash
#
# NASA Worldview
#
# This code was originally developed at NASA/Goddard Space Flight Center for
# the Earth Science Data and Information System (ESDIS) project.
#
# Copyright (C) 2013 - 2014 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#

BASE_DIR=$(dirname "$0")
PIP="$BASE_DIR"/python/bin/pip

# virtualenv 1.11 is broken
# http://stackoverflow.com/questions/20916712/cannot-create-virtualenv-instance-in-python-2-7-5-because-of-pip-installation-er
if [ ! -e /usr/bin/virtualenv ] && [ ! -e /usr/local/bin/virtualenv ] ; then
    echo "Install virtualenv before running this script" >&2
fi
virtualenv python
$PIP install xmltodict

