#!/bin/bash

set -e

PROG=$(basename "$0")
BASE_DIR=$(dirname "$0")

echo -n "$PROG: Removing node_modules... "
rm -rf "$BASE_DIR/node_modules"
echo "done."

echo -n "$PROG: Removing python virtualenv... "
rm -rf "$BASE_DIR"/python
echo "done."

echo -n "$PROG: Removing build directory... "
rm -rf "$BASE_DIR"/build
echo "done."

echo -n "$PROG: Removing dist directory... "
rm -rf "$BASE_DIR"/dist
echo "done."

echo -n "$PROG: Removing any other non-source files... "
rm -f npm-debug.log
rm -rf src/conf/*
rm -rf src/config/*
echo "done."
