#!/bin/bash
#
# NASA Worldview
#
# This code was originally developed at NASA/Goddard Space Flight Center for
# the Earth Science Data and Information System (ESDIS) project.
#
# Copyright (C) 2013 - 2014 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#

set -e

BASE_DIR=$(dirname "$0")

( \
    cd $BASE_DIR; virtualenv python ; python/bin/pip install \
    xmltodict \
)
