export const LOADING_START = 'LOADING/START';
export const LOADING_STOP = 'LOADING/STOP';
export const LOADING_LOADING_LIST_ADD = 'LOADING/LOADING_LIST_ADD';
export const LOADING_LOADED_LIST_ADD = 'LOADING/LOADED_LIST_ADD';
