export const TOGGLE_ON_OFF = 'CHARTING/TOGGLE_ON_OFF';
export const TOGGLE_AOI_ON_OFF = 'CHARTING/TOGGLE_AOI_ON_OFF';
export const TOGGLE_DATE_MODE = 'CHARTING/TOGGLE_DATE_MODE';
export const UPDATE_START_DATE = 'CHARTING/UPDATE_START_DATE';
export const UPDATE_END_DATE = 'CHARTING/UPDATE_END_DATE';
