#!/bin/bash
#
# NASA Worldview
# 
# This code was originally developed at NASA/Goddard Space Flight Center for
# the Earth Science Data and Information System (ESDIS) project. 
#
# Copyright (C) 2013 United States Government as represented by the 
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
set -e

PROG=$(basename "$0")

die() {
    echo "$PROG: ERROR: $@" >&2
    exit 1
}

SOURCE_DIR=~/src/worldview

[ -e "$SOURCE_DIR" ] || die "No such directory: $SOURCE_DIR"

( cd "$SOURCE_DIR" ; git pull )
ant -f "$SOURCE_DIR/build.xml" deploy





