export const CLEAR_COORDINATES = 'GEOSEARCH/CLEAR_COORDINATES';
export const SELECT_COORDINATES_TO_FLY = 'GEOSEARCH/SELECT_COORDINATES_TO_FLY';
export const TOGGLE_REVERSE_GEOCODE_ACTIVE = 'GEOSEARCH/TOGGLE_REVERSE_GEOCODE_ACTIVE';
export const TOGGLE_SHOW_GEOSEARCH = 'GEOSEARCH/TOGGLE_SHOW_GEOSEARCH';
export const UPDATE_ACTIVE_MARKER = 'GEOSEARCH/UPDATE_ACTIVE_MARKER';
