# FROM mcr.microsoft.com/playwright:focal

# WORKDIR /build

# RUN mkdir -p /build/node_modules && \
#     npm install \
#     @playwright/test \
#     playwright-firefox

# VOLUME /build/node_modules