export const REQUEST_VECTORSTYLE = 'VECTORSTYLES/REQUEST_VECTORSTYLE';
export const REQUEST_VECTORSTYLE_START = 'VECTORSTYLES/REQUEST_VECTORSTYLE_START';
export const REQUEST_VECTORSTYLE_SUCCESS = 'VECTORSTYLES/REQUEST_VECTORSTYLE_SUCCESS';
export const REQUEST_VECTORSTYLE_FAILURE = 'VECTORSTYLES/REQUEST_VECTORSTYLE_FAILURE';

export const VECTORSTYLE_CHANGE = 'VECTORSTYLES/CHANGE_OF_ACTIVE_VECTORSTYLE';
export const SET_FILTER_RANGE = 'VECTORSTYLES/SET_FILTER_RANGE';
export const CLEAR_VECTORSTYLE = 'VECTORSTYLES/CLEAR_VECTORSTYLE';
export const SET_VECTORSTYLE = 'VECTORSTYLES/SET_VECTORSTYLE';
export const LOADED_CUSTOM_VECTORSTYLES = 'VECTORSTYLES/LOADED_CUSTOM_VECTORSTYLES';
