export const REQUEST_VECTORSTYLE = 'VECTORSTYLES/REQUEST_VECTORSTYLE';
export const REQUEST_VECTORSTYLE_START = 'VECTORSTYLES/REQUEST_VECTORSTYLE_START';
export const REQUEST_VECTORSTYLE_SUCCESS = 'VECTORSTYLES/REQUEST_VECTORSTYLE_SUCCESS';
export const REQUEST_VECTORSTYLE_FAILURE = 'VECTORSTYLES/REQUEST_VECTORSTYLE_FAILURE';

export const VECTORSTYLE_CHANGE = 'VECTORSTYLES/CHANGE_OF_ACTIVE_VECTORSTYLE';
export const SET_RANGE_AND_SQUASH = 'VECTORSTYLES/SET_RANGE_AND_SQUASH';
export const CLEAR_CUSTOM = 'VECTORSTYLES/CLEAR_CUSTOM';
export const SET_CUSTOM = 'VECTORSTYLES/SET_CUSTOM';
export const LOADED_CUSTOM_VECTORSTYLES = 'VECTORSTYLES/LOADED_CUSTOM_VECTORSTYLES';
