export const CONFIG_HAS_BEEN_LOADED = 'CONFIG_AND_MODELS_HAVE_BEEN_LOADED';
export const UPDATE_IN_LEGACY_STATE =
  'AN_UPDATE_TO_LEGACY_STATE_MODULE_HAS_OCCURED';
export const INIT_COMPLETE = 'LEGACY_MODELS_INIT_COMPLETE';
