export const TOGGLE_INFINITE_WRAP = 'SETTINGS/INFINITE_WRAP_TOGGLE';
export const TOGGLE_OVERVIEW_MAP = 'SETTINGS/TOGGLE_OVERVIEW_MAP';
export const TOGGLE_SHOW_DATELINE = 'SETTINGS/TOGGLE_SHOW_DATELINE';
export const TOGGLE_VISIBLE_DATELINES = 'SETTINGS/TOGGLE_VISIBLE_DATELINES';
export const TOGGLE_DAY_NIGHT_MODE = 'SETTINGS/TOGGLE_DAY_NIGHT_MODE';
