export const REQUEST_NOTIFICATIONS = 'REQUEST_APP_NOTIFICATIONS';
export const REQUEST_NOTIFICATIONS_START = 'REQUEST_APP_NOTIFICATIONS_START';
export const REQUEST_NOTIFICATIONS_SUCCESS =
  'REQUEST_APP_NOTIFICATIONS_SUCCESS';
export const REQUEST_NOTIFICATIONS_FAILURE =
  'REQUEST_APP_NOTIFICATIONS_FAILURE';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATION_RESPONSE';
export const NOTIFICATIONS_SEEN = 'NOTIFICATIONS_HAVE_BEEN_SEEN';
export const STATUS_REQUEST_URL =
  'https://status.earthdata.nasa.gov/api/v1/notifications?domain=https%3A%2F%2Fworldview.earthdata.nasa.gov';
