export const TOGGLE_URL = 'TOGGLE_SHARE_LINK';
export const UPDATE_PERMALINK = 'UPDATE_PERMALINK';

export const REQUEST_SHORT_LINK_START = 'REQUEST_BITLY_SHORTENED_LINK_START';
export const REQUEST_SHORT_LINK_SUCCESS =
  'REQUEST_BITLY_SHORTENED_LINK_SUCCESS';
export const REQUEST_SHORT_LINKE_FAILURE =
  'REQUEST_BITLY_SHORTENED_LINK_FAILURE';
export const REQUEST_SHORT_LINK = 'REQUEST_BITLY_SHORTENED_LINK';
