export const CLEAR_ROTATE = 'MAP/CLEAR_ROTATE';
export const UPDATE_MAP_EXTENT = 'MAP/UPDATE_MAP_EXTENT';
export const UPDATE_MAP_UI = 'MAP/UPDATE_MAP_UI';
export const UPDATE_MAP_ROTATION = 'MAP/UPDATE_ROTATION';
export const RENDERED = 'MAP/RENDERED';
export const FITTED_TO_LEADING_EXTENT = 'MAP/FITTED_TO_LEADING_EXTENT';
export const CHANGE_CURSOR = 'MAP/CHANGE_CURSOR';
export const REFRESH_ROTATE = 'MAP/REFRESH_ROTATE';
