export const RUNNING_DATA = 'MAP/RUNNING_DATA';
export const CLEAR_RUNNING_DATA = 'MAP/CLEAR_RUNNING_DATA';
export const CLEAR_ROTATE = 'MAP/CLEAR_ROTATE';
export const UPDATE_MAP_EXTENT = 'MAP/UPDATE_MAP_EXTENT';
export const UPDATE_MAP_UI = 'MAP/UPDATE_MAP_UI';
export const UPDATE_MAP_ROTATION = 'MAP/UPDATE_ROTATION';
