export const REQUEST_PALETTE = 'PALETTES/REQUEST_PALETTE';
export const REQUEST_PALETTE_START = 'PALETTES/REQUEST_PALETTE_START';
export const REQUEST_PALETTE_SUCCESS = 'PALETTES/REQUEST_PALETTE_SUCCESS';
export const REQUEST_PALETTE_FAILURE = 'PALETTES/REQUEST_PALETTE_FAILURE';
export const SET_DISABLED_CLASSIFICATION = 'PALETTES/SET_DISABLED_CLASSIFICATION';
export const PALETTE_CHANGE = 'PALETTES/CHANGE_OF_ACTIVE_PALETTE';
export const SET_THRESHOLD_RANGE_AND_SQUASH = 'PALETTES/SET_THRESHOLD_RANGE_AND_SQUASH';
export const CLEAR_CUSTOM = 'PALETTES/CLEAR_CUSTOM';
export const CLEAR_CUSTOMS = 'PALETTES/CLEAR_CUSTOMS';
export const SET_CUSTOM = 'PALETTES/SET_CUSTOM';
export const LOADED_CUSTOM_PALETTES = 'PALETTES/LOADED_CUSTOM_PALETTES';
export const BULK_PALETTE_RENDERING_SUCCESS =
  'PALETTES/BULK_PALETTE_RENDERING_SUCCESS';

export const PALETTE_STRINGS_PERMALINK_ARRAY = [
  'palette',
  'squash',
  'min',
  'max',
  'disabled'
];
export const CUSTOM_PALETTE_TYPE_ARRAY = ['custom', 'squash', 'min', 'max', 'disabled'];
