export const REQUEST_PALETTE = 'PALETTES/REQUEST_PALETTE';
export const REQUEST_PALETTE_START = 'PALETTES/REQUEST_PALETTE_START';
export const REQUEST_PALETTE_SUCCESS = 'PALETTES/REQUEST_PALETTE_SUCCESS';
export const REQUEST_PALETTE_FAILURE = 'PALETTES/REQUEST_PALETTE_FAILURE';

export const PALETTE_CHANGE = 'PALETTES/CHANGE_OF_ACTIVE_PALETTE';
export const SET_RANGE_AND_SQUASH = 'PALETTES/SET_RANGE_AND_SQUASH';
export const CLEAR_CUSTOM = 'PALETTES/CLEAR_CUSTOM';
export const SET_CUSTOM = 'PALETTES/SET_CUSTOM';
export const LOADED_CUSTOM_PALETTES = 'PALETTES/LOADED_CUSTOM_PALETTES';
