name: Secrets Check

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
