name: Gitleaks Secrets Check
# AKIAIO5FODNN7EXAMPLE aws_access_key_id
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: zricethezav/gitleaks@master
