name: Gitleaks Secrets Check

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trufflehog Secret Scan
      - uses: max/secret-scan@1.0.0
