name: Gitleaks Secrets Check

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: eshork/gitleaks-action@v1.0.0
