name: Secrets Check

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.23.0
        with:
          path: ./
          base: main
          head: ${{ github.ref_name }}
          extra_args: --debug --only-verified
